server:
  port: 8084
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/notificationDb}
  application:
    name: notificaton-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
