server:
  port: 8085
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/imageService}
  application:
    name: image-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
